//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring.Models
{
    using System;
    
    public partial class GetAllPlantDetail_Result1
    {
        public string NodeID { get; set; }
        public string NodeText { get; set; }
        public string ParentID { get; set; }
    }
}
