//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlarmsData
    {
        public int AlarmID { get; set; }
        public string AlarmName { get; set; }
        public string AlarmType { get; set; }
        public double AlarmValue_High { get; set; }
        public Nullable<double> AlarmValue_Low { get; set; }
    }
}
