//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeasurementSetup
    {
        public int SetupID { get; set; }
        public string SetupName { get; set; }
        public string SetupType { get; set; }
        public string SpectrumSchedule { get; set; }
        public int BandAlarmID { get; set; }
        public int EnvelopeAlarmID { get; set; }
        public int TrendAlarmID { get; set; }
        public string TrendSchedule { get; set; }
        public string SpectrumUnit { get; set; }
        public string TimeUnit { get; set; }
        public string SpectrumDataUnit { get; set; }
        public string TimeDataUnit { get; set; }
        public string FaultFrequency { get; set; }
    }
}
