//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOveralldata
    {
        public int ID { get; set; }
        public int RecordID { get; set; }
        public string SensorID { get; set; }
        public double Overallvalue { get; set; }
        public string ParentID { get; set; }
    
        public virtual tblRecordedData tblRecordedData { get; set; }
    }
}
