//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlantMaster
    {
        public int ID { get; set; }
        public string SensorID { get; set; }
        public string PointID { get; set; }
        public string MachineID { get; set; }
        public string TrainID { get; set; }
        public string AreaID { get; set; }
        public string PlantID { get; set; }
        public string UserID { get; set; }
    
        public virtual tblArea tblArea { get; set; }
        public virtual tblMachine tblMachine { get; set; }
        public virtual tblPlant tblPlant { get; set; }
        public virtual tblPoint tblPoint { get; set; }
        public virtual tblSensor tblSensor { get; set; }
        public virtual tblTrain tblTrain { get; set; }
        public virtual tblUserRegister tblUserRegister { get; set; }
    }
}
